import { _operator } from '../src/operation';

const caseMap = {
  'add': [
    [7, 8, 15],
    [7, -1, 6],
    [7, '5', 12],
    [7, '', 7],
    [7, 'xy', NaN],
    [7, true, 8],
    [7, false, 7],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 7, 'xyz7'],
    ['xyz', -1, 'xyz-1'],
    ['xyz', '7', 'xyz7'],
    ['xyz', true, 'xyztrue'],
    ['xyz', false, 'xyzfalse'],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 7, true],
    [true, -1, false],
    [false, 0, false],
    [false, -1, true],
    [true, '5', true],
    [true, '-1', false],
    [false, '', false],
    [false, '5', true],
    [true, 'xy', false],
    [true, true, true],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 5], 7, [10, 12]],
    [[3, 'ab'], 7, [10, 'ab7']],
    [[3, 5], '5', [8, 10]],
    [[3, 'ab'], '5', [8, 'ab5']],
    [[3, 'ab'], 'xy', [NaN, 'abxy']],
    [[3, 5], true, [4, 6]],
    [[3, 'ab'], false, [3, 'abfalse']],
    [[3, 5], [3, 5], [6, 10]],
    [[3, 5], [3, 'ab'], [6, NaN]],
    [[3, 'ab'], [3, 5], [6, 'ab5']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 5, 'b': 'z'}, 7, {'a': 12, 'b': 'z7'}],
    [{'a': 5, 'b': 'z'}, 'xy', {'a': NaN, 'b': 'zxy'}],
    [{'a': 5, 'b': 'z'}, true, {'a': 6, 'b': 'ztrue'}],
    [{'a': 5, 'b': 'z'}, false, {'a': 5, 'b': 'zfalse'}],
    [{'a': 5, 'b': 'z'}, [3, 5], null, 'anycase'],
    [{'a': 5, 'b': 8}, {'a': 5, 'b': 'z'}, {'a': 10, 'b': NaN}],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 8}, {'a': 10, 'b': 'z8'}],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, {'a': 10, 'b': 'zz'}],
  ],
  'subtract': [
    [7, 5, 2],
    [7, -1, 8],
    [7, '5', 2],
    [7, '', 7],
    [7, 'xy', NaN],
    [7, true, 6],
    [7, false, 7],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz2', 2, 'xyz'],
    ['xyz', 'yz', 'x'],
    ['xyz', true, 'xyz'],
    ['xfalse', false, 'x'],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 7, true],
    [true, 1, false],
    [false, 0, false],
    [false, -1, true],
    [true, '5', true],
    [true, '1', false],
    [false, '', false],
    [false, '5', true],
    [true, 'xy', false],
    [true, true, false],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 5], 7, [-4, -2]],
    [[3, 'ab7'], 7, [-4, 'ab']],
    [[3, 5], '5', [-2, 0]],
    [[3, 'ab5'], '5', [-2, 'ab']],
    [[3, 'ab'], 'xy', [NaN, 'ab']],
    [[3, 5], true, [2, 4]],
    [[3, 'abfalse'], false, [3, 'ab']],
    [[3, 5], [2, 6], [1, -1]],
    [[3, 5], [3, 'ab'], [0, NaN]],
    [[3, 'ab5'], [3, 5], [0, 'ab']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 5, 'b': 'z7'}, 7, {'a': -2, 'b': 'z'}],
    [{'a': 5, 'b': 'xyz'}, 'yz', {'a': NaN, 'b': 'x'}],
    [{'a': 5, 'b': 'z'}, true, {'a': 4, 'b': 'z'}],
    [{'a': 5, 'b': 'zfalse'}, false, {'a': 5, 'b': 'z'}],
    [{'a': 5, 'b': 8}, [3, 5], null, 'anycase'],
    [{'a': 5, 'b': 8}, {'a': 5, 'b': 'z'}, {'a': 0, 'b': NaN}],
    [{'a': 5, 'b': 'z8'}, {'a': 5, 'b': 8}, {'a': 0, 'b': 'z'}],
  ],
  'multiply': [
    [7, 8, 56],
    [7, -1, -7],
    [7, '5', 35],
    [7, '', 0],
    [7, 'xy', NaN],
    [7, true, 7],
    [7, false, 0],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 2, 'xyzxyz'],
    ['xyz', 0, ''],
    ['xyz', -1, ''],
    ['xyz', 'xy', 'xy'],
    ['xyz', 'xz', ''],
    ['xyz', '', ''],
    ['xyz', true, 'xyz'],
    ['xyz', false, ''],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 7, true],
    [true, 0, false],
    [false, 7, false],
    [true, '5', true],
    [true, '', false],
    [false, '', false],
    [true, 'xy', false],
    [true, true, true],
    [true, false, false],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 5], 7, [21, 35]],
    [[3, 'ab'], 5, [15, 'ababababab']],
    [[3, 5], '5', [15, 25]],
    [[3, 'xyz'], 'xy', [NaN, 'xy']],
    [[3, 5], true, [3, 5]],
    [[3, 'ab'], false, [0, '']],
    [[3, 5], [3, 5], [9, 25]],
    [[3, 5], [3, 'ab'], [9, NaN]],
    [[3, 'ab'], [3, 5], [9, 'ababababab']],
    [[3, 'abc'], [3, 'ab'], [9, 'ab']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 5, 'b': 'z'}, 7, {'a': 35, 'b': 'zzzzzzz'}],
    [{'a': 5, 'b': 'z'}, '5', {'a': 25, 'b': ''}],
    [{'a': 5, 'b': 'xyz'}, 'xy', {'a': NaN, 'b': 'xy'}],
    [{'a': 5, 'b': 'z'}, true, {'a': 5, 'b': 'z'}],
    [{'a': 5, 'b': 'z'}, false, {'a': 0, 'b': ''}],
    [{'a': 5, 'b': 'z'}, [3, 5], null, 'anycase'],
    [{'a': 5, 'b': 8}, {'a': 5, 'b': 'z'}, {'a': 25, 'b': NaN}],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 8}, {'a': 25, 'b': 'zzzzzzzz'}],
  ],
  'divide': [
    [5, 2, 2.5],
    [5, 0, Infinity],
    [7, '5', 1.4],
    [7, '', Infinity],
    [7, 'xy', NaN],
    [7, true, 7],
    [7, false, Infinity],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 3, 'x'],
    ['xyz', 0, ''],
    ['xyz', -1, ''],
    ['xyz', 'xy', 'z'],
    ['xyz', 'xz', 'xyz'],
    ['xyz', '', ''],
    ['xyz', true, 'xyz'],
    ['xyz', false, ''],
    ['xy', [3, 5], '', 'anycase'],
    ['xy', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 7, true],
    [true, 0, false],
    [false, 7, false],
    [true, '5', true],
    [true, '', false],
    [false, '5', false],
    [true, 'xy', false],
    [true, true, true],
    [true, false, false],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 7], 5, [0.6, 1.4]],
    [[3, 'xyz'], 3, [1, 'x']],
    [[3, 5], '5', [0.6, 1]],
    [[3, 'xyz'], 'xy', [NaN, 'z']],
    [[3, 5], true, [3, 5]],
    [[3, 'ab'], false, [Infinity, '']],
    [[3, 7], [2, 5], [1.5, 1.4]],
    [[3, 5], [2, 'ab'], [1.5, NaN]],
    [[3, 'xyz'], [2, 'xy'], [1.5, 'z']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 6, 'b': 'xyz'}, 3, {'a': 2, 'b': 'x'}],
    [{'a': 6, 'b': 'xyz'}, 'xy', {'a': NaN, 'b': 'z'}],
    [{'a': 6, 'b': 'xyz'}, true, {'a': 6, 'b': 'xyz'}],
    [{'a': 6, 'b': 'xyz'}, false, {'a': Infinity, 'b': ''}],
    [{'a': 6, 'b': 'xyz'}, [3, 5], null, 'anycase'],
    [{'a': 6, 'b': 8}, {'a': 5, 'b': 'xy'}, {'a': 1.2, 'b': NaN}],
    [{'a': 6, 'b': 'xyz'}, {'a': 5, 'b': 3}, {'a': 1.2, 'b': 'x'}],
  ],
  'power': [
    [5, 2, 25],
    [5, 0, 1],
    [5, -1, 0.2],
    [5, '2', 25],
    [5, '', 1],
    [5, 'xy', NaN],
    [5, true, 5],
    [5, false, 1],
    [5, [3, 5], NaN, 'anycase'],
    [5, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 2, 'xyz'],
    ['xyz', 0, ''],
    ['xyz', -1, ''],
    ['xyz', 'xz', 'xz'],
    ['xyz', '', ''],
    ['xyz', true, 'xyz'],
    ['xyz', false, ''],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 7, true],
    [false, 7, false],
    [false, 0, true],
    [true, 'xy', true],
    [false, '', true],
    [true, true, true],
    [true, false, true],
    [false, true, false],
    [false, false, true],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 5], 2, [9, 25]],
    [[3, 'ab'], 2, [9, 'ab']],
    [[3, 5], '2', [9, 25]],
    [[3, 'ab'], 'xy', [NaN, '']],
    [[3, 5], true, [3, 5]],
    [[3, 'ab'], false, [1, '']],
    [[3, 5], [3, 2], [27, 25]],
    [[3, 5], [3, 'xz'], [27, NaN]],
    [[3, 'xyz'], [3, 'xz'], [27, 'xz']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 3, 'b': 'xyz'}, 2, {'a': 9, 'b': 'xyz'}],
    [{'a': 3, 'b': 'xyz'}, 'xz', {'a': NaN, 'b': 'xz'}],
    [{'a': 3, 'b': 'xyz'}, true, {'a': 3, 'b': 'xyz'}],
    [{'a': 3, 'b': 'xyz'}, false, {'a': 1, 'b': ''}],
    [{'a': 3, 'b': 'xyz'}, [3, 5], null, 'anycase'],
    [{'a': 3, 'b': 5}, {'a': 2, 'b': 'xz'}, {'a': 9, 'b': NaN}],
    [{'a': 3, 'b': 'xyz'}, {'a': 2, 'b': 3}, {'a': 9, 'b': 'xyz'}],
  ],
  'modulo': [
    [5, 2, 1],
    [5, 0, NaN],
    [5, '2', 1],
    [5, '', NaN],
    [7, 'xy', NaN],
    [5, true, 0],
    [5, false, NaN],
    [5, [3, 5], NaN, 'anycase'],
    [5, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['abcde', 3, 'de'],
    ['abcde', 0, ''],
    ['abcde', 'bc', ''],
    ['abcde', '', ''],
    ['abcde', true, ''],
    ['abcde', false, ''],
    ['abcde', [3, 5], '', 'anycase'],
    ['abcde', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 2, true],
    [true, 1, false],
    [true, 0, false],
    [false, 1, false],
    [true, 'xy', false],
    [true, '', false],
    [false, 'xy', false],
    [true, true, false],
    [true, false, false],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 5], 3, [0, 2]],
    [[3, 'abcde'], 3, [0, 'de']],
    [[3, 5], '3', [0, 2]],
    [[3, 'abcde'], 'bc', [NaN, '']],
    [[3, 5], true, [0, 0]],
    [[3, 'ab'], false, [NaN, '']],
    [[3, 5], [2, 3], [1, 2]],
    [[3, 5], [2, 'ab'], [1, NaN]],
    [[3, 'abced'], [2, 'bc'], [1, '']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 5, 'b': 'abcde'}, 3, {'a': 2, 'b': 'de'}],
    [{'a': 5, 'b': 'abcde'}, 'bc', {'a': NaN, 'b': ''}],
    [{'a': 5, 'b': 'abcde'}, true, {'a': 0, 'b': ''}],
    [{'a': 5, 'b': 'z'}, [3, 5], null, 'anycase'],
    [{'a': 5, 'b': 8}, {'a': 3, 'b': 'z'}, {'a': 2, 'b': NaN}],
    [{'a': 5, 'b': 'abcde'}, {'a': 3, 'b': 3}, {'a': 2, 'b': 'de'}],
  ],
  'bit_and': [
    [21, 7, 5],
    [21, -1, 21],
    [21, '7', 5],
    [21, 'xyz', NaN],
    [21, true, 1],
    [21, false, 0],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 1, 'xyz'],
    ['xyz', 0, ''],
    ['xyz', 'z', 'xyz'],
    ['xyz', '', ''],
    ['xyz', true, 'xyz'],
    ['xyz', false, ''],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 2, true],
    [true, 0, false],
    [true, 'z', true],
    [true, '', false],
    [true, true, true],
    [true, false, false],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[21, 6], 7, [5, 6]],
    [[21, 'xyz'], 7, [5, 'xyz']],
    [[21, 6], '7', [5, 6]],
    [[21, 'xyz'], 'z', [NaN, 'xyz']],
    [[21, 6], true, [1, 0]],
    [[21, 'xyz'], true, [1, 'xyz']],
    [[21, 11], [7, 10], [5, 10]],
    [[21, 11], [7, 'ab'], [5, NaN]],
    [[21, 'xyz'], [7, 'ab'], [5, 'xyz']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 21, 'b': 'xyz'}, 7, {'a': 5, 'b': 'xyz'}],
    [{'a': 21, 'b': 'xyz'}, 'xy', {'a': NaN, 'b': 'xyz'}],
    [{'a': 21, 'b': 'xyz'}, true, {'a': 1, 'b': 'xyz'}],
    [{'a': 21, 'b': 'xyz'}, false, {'a': 0, 'b': ''}],
    [{'a': 21, 'b': 'z'}, [3, 5], null, 'anycase'],
    [{'a': 21, 'b': 8}, {'a': 7, 'b': 'xyz'}, {'a': 5, 'b': NaN}],
    [{'a': 21, 'b': 'xyz'}, {'a': 7, 'b': 8}, {'a': 5, 'b': 'xyz'}],
  ],
  'bit_or': [
    [21, 7, 23],
    [21, '7', 23],
    [21, 'xyz', NaN],
    [20, true, 21],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['', 1, ''],
    ['xyz', 0, 'xyz'],
    ['', 'z', ''],
    ['xyz', '', 'xyz'],
    ['', true, ''],
    ['xyz', false, 'xyz'],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 0, true],
    [false, 2, true],
    [false, 0, false],
    [true, '', true],
    [false, 'z', true],
    [false, '', false],
    [true, true, true],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[21, 6], 7, [23, 7]],
    [[21, 'xyz'], 7, [23, 'xyz']],
    [[21, 6], '7', [23, 7]],
    [[21, 'xyz'], 'z', [NaN, 'xyz']],
    [[20, 6], true, [21, 7]],
    [[20, 'xyz'], false, [20, 'xyz']],
    [[21, 11], [7, 5], [23, 15]],
    [[21, 11], [7, 'z'], [23, NaN]],
    [[21, 'xyz'], [7, 'z'], [23, 'xyz']],
    [[3, 5], {'a': 5, 'b': 8}, null, 'anycase'],
    [{'a': 21, 'b': 'xyz'}, 7, {'a': 23, 'b': 'xyz'}],
    [{'a': 21, 'b': 'xyz'}, 'z', {'a': NaN, 'b': 'xyz'}],
    [{'a': 20, 'b': 'xyz'}, true, {'a': 21, 'b': 'xyz'}],
    [{'a': 20, 'b': 'xyz'}, false, {'a': 20, 'b': 'xyz'}],
    [{'a': 5, 'b': 'z'}, [3, 5], null, 'anycase'],
    [{'a': 21, 'b': 6}, {'a': 7, 'b': 'z'}, {'a': 23, 'b': NaN}],
    [{'a': 21, 'b': 'xyz'}, {'a': 7, 'b': 7}, {'a': 23, 'b': 'xyz'}],
  ],
  'bit_xor': [
    [21, 7, 18],
    [21, '7', 18],
    [21, 'xyz', NaN],
    [21, true, 20],
    [21, [3, 5], NaN, 'anycase'],
    [21, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 7, ''],
    ['xyz', 0, 'xyz'],
    ['', 0, ''],
    ['xyz', 'z', ''],
    ['xyz', '', 'xyz'],
    ['', '', ''],
    ['xyz', true, ''],
    ['xyz', false, 'xyz'],
    ['', false, ''],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 7, false],
    [true, 0, true],
    [false, 7, true],
    [false, 0, false],
    [true, 'z', false],
    [true, '', true],
    [false, 'z', true],
    [false, '', false],
    [true, true, false],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[21, 6], 7, [18, 1]],
    [[21, 'xyz'], 7, [18, '']],
    [[21, 6], '7', [18, 1]],
    [[21, 'xyz'], 'z', [NaN, '']],
    [[21, 6], true, [20, 7]],
    [[21, 'xyz'], false, [21, 'xyz']],
    [[21, 6], [7, 5], [18, 3]],
    [[21, 6], [7, 'z'], [18, NaN]],
    [[21, 'xyz'], [7, 'z'], [18, '']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 21, 'b': 'xyz'}, 7, {'a': 18, 'b': ''}],
    [{'a': 21, 'b': 'xyz'}, 'z', {'a': NaN, 'b': ''}],
    [{'a': 21, 'b': 'xyz'}, true, {'a': 20, 'b': ''}],
    [{'a': 21, 'b': 'xyz'}, false, {'a': 21, 'b': 'xyz'}],
    [{'a': 5, 'b': 'z'}, [3, 5], null, 'anycase'],
    [{'a': 21, 'b': 6}, {'a': 7, 'b': 'z'}, {'a': 18, 'b': NaN}],
    [{'a': 21, 'b': 'z'}, {'a': 7, 'b': 8}, {'a': 18, 'b': ''}],
  ],
  'bit_shift': [
    [7, 2, 28],
    [7, '2', 28],
    [7, 'xyz', NaN],
    [7, true, 14],
    [7, false, 7],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 2, 'xyz  '],
    ['xyz', '2', 'xyz  '],
    ['xyz', 'z', ''],
    ['xyz', true, 'xyz '],
    ['xyz', false, 'xyz'],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 2, true],
    [true, 0, true],
    [false, 2, false],
    [true, '2', true],
    [true, '', true],
    [false, '2', false],
    [true, 'xy', false],
    [true, true, true],
    [true, false, true],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[3, 5], 2, [12, 20]],
    [[3, 'xyz'], 2, [12, 'xyz  ']],
    [[3, 5], '2', [12, 20]],
    [[3, 'xyz'], 'z', [NaN, '']],
    [[3, 5], true, [6, 10]],
    [[3, 'xyz'], false, [3, 'xyz']],
    [[3, 5], [2, 3], [12, 40]],
    [[3, 5], [2, 'z'], [12, NaN]],
    [[3, 'xyz'], [2, 'z'], [12, '']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 3, 'b': 'xyz'}, 2, {'a': 12, 'b': 'xyz  '}],
    [{'a': 3, 'b': 'xyz'}, 'z', {'a': NaN, 'b': ''}],
    [{'a': 3, 'b': 'xyz'}, true, {'a': 6, 'b': 'xyz '}],
    [{'a': 3, 'b': 'xyz'}, [3, 5], null, 'anycase'],
    [{'a': 3, 'b': 5}, {'a': 2, 'b': 'z'}, {'a': 12, 'b': NaN}],
    [{'a': 3, 'b': 'xyz'}, {'a': 2, 'b': 1}, {'a': 12, 'b': 'xyz '}],
  ],
  'bit_unshift': [
    [7, 1, 3],
    [7, '1', 3],
    [7, 'xyz', NaN],
    [7, true, 3],
    [7, false, 7],
    [7, [3, 5], NaN, 'anycase'],
    [7, {'a': 5, 'b': 'z'}, NaN, 'anycase'],
    ['xyz', 1, 'xy'],
    ['xyz', '1', 'xy'],
    ['xyz', 'z', ''],
    ['xyz', true, 'xy'],
    ['xyz', false, 'xyz'],
    ['xyz', [3, 5], '', 'anycase'],
    ['xyz', {'a': 5, 'b': 'z'}, '', 'anycase'],
    [true, 1, false],
    [true, 0, true],
    [true, '1', false],
    [true, '', true],
    [true, 'z', false],
    [true, true, false],
    [true, false, true],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false, 'anycase'],
    [true, {'a': 5, 'b': 'z'}, false, 'anycase'],
    [[7, 5], 1, [3, 2]],
    [[7, 'xyz'], 1, [3, 'xy']],
    [[7, 5], '1', [3, 2]],
    [[7, 'xyz'], 'z', [NaN, '']],
    [[7, 5], true, [3, 2]],
    [[7, 'xyz'], true, [3, 'xy']],
    [[7, 5], [1, 2], [3, 1]],
    [[7, 5], [1, 'z'], [3, NaN]],
    [[7, 'xyz'], [1, 'z'], [3, '']],
    [[3, 5], {'a': 5, 'b': 'z'}, null, 'anycase'],
    [{'a': 7, 'b': 'xyz'}, 1, {'a': 3, 'b': 'xy'}],
    [{'a': 7, 'b': 'xyz'}, 'z', {'a': NaN, 'b': ''}],
    [{'a': 7, 'b': 'xyz'}, true, {'a': 3, 'b': 'xy'}],
    [{'a': 7, 'b': 'xyz'}, [3, 5], null, 'anycase'],
    [{'a': 7, 'b': 5}, {'a': 1, 'b': 'z'}, {'a': 3, 'b': NaN}],
    [{'a': 7, 'b': 'xyz'}, {'a': 1, 'b': 2}, {'a': 3, 'b': 'x'}],
  ],
  'not': [
    [7, undefined, false],
    [0, undefined, true],
    ['xyz', undefined, false],
    ['', undefined, true],
    [true, undefined, false],
    [false, undefined, true],
    [[3, 5], undefined, false],
    [[], undefined, true],
    [{'a': 5, 'b': 8}, undefined, false],
    [{}, undefined, true],
  ],
  'logical_and': [
    [7, 8, true],
    [7, 0, false],
    [7, 'xyz', true],
    [7, '', false],
    [7, true, true],
    [7, false, false],
    [7, [3, 5], true],
    [7, [], false],
    [7, {'a': 5, 'b': 'z'}, true],
    [7, {}, false],
    ['xyz', 7, true],
    ['xyz', 0, false],
    ['xyz', 'abc', true],
    ['xyz', '', false],
    ['xyz', true, true],
    ['xyz', false, false],
    ['xyz', [3, 5], true],
    ['xyz', [], false],
    ['xyz', {'a': 5, 'b': 'z'}, true],
    ['xyz', {}, false],
    [true, 7, true],
    [true, 0, false],
    [true, 'xyz', true],
    [true, '', false],
    [true, true, true],
    [true, false, false],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], true],
    [true, [], false],
    [true, {'a': 5, 'b': 'z'}, true],
    [true, {}, false],
    [[3, 5], 7, true],
    [[3, 5], 0, false],
    [[3, 5], 'xyz', true],
    [[3, 5], '', false],
    [[3, 5], true, true],
    [[3, 5], false, false],
    [[3, 5], [2, 3], true],
    [[3, 5], [], false],
    [[3, 5], {'a': 5, 'b': 'z'}, true],
    [[3, 5], {}, false],
    [{'a': 5, 'b': 'z'}, 7, true],
    [{'a': 5, 'b': 'z'}, 0, false],
    [{'a': 5, 'b': 'z'}, 'xyz', true],
    [{'a': 5, 'b': 'z'}, '', false],
    [{'a': 5, 'b': 'z'}, true, true],
    [{'a': 5, 'b': 'z'}, false, false],
    [{'a': 5, 'b': 'z'}, [3, 5], true],
    [{'a': 5, 'b': 'z'}, [], false],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, true],
    [{'a': 5, 'b': 'z'}, {}, false],
  ],
  'logical_or': [
    [7, 0, true],
    [0, 0, false],
    [7, '', true],
    [0, '', false],
    [7, false, true],
    [0, false, false],
    [7, [], true],
    [0, [], false],
    [7, {}, true],
    [0, {}, false],
    ['xyz', 0, true],
    ['', 0, false],
    ['xyz', '', true],
    ['', '', false],
    ['xyz', false, true],
    ['', false, false],
    ['xyz', [], true],
    ['', [], false],
    ['xyz', {}, true],
    ['', {}, false],
    [true, 0, true],
    [false, 0, false],
    [true, '', true],
    [false, '', false],
    [true, true, true],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [], true],
    [false, [], false],
    [true, {}, true],
    [false, {}, false],
    [[3, 5], 0, true],
    [[], 0, false],
    [[3, 5], '', true],
    [[], '', false],
    [[3, 5], false, true],
    [[], false, false],
    [[3, 5], [], true],
    [[], [], false],
    [[3, 5], {}, true],
    [[], {}, false],
    [{'a': 5, 'b': 'z'}, 0, true],
    [{}, 0, false],
    [{'a': 5, 'b': 'z'}, '', true],
    [{}, '', false],
    [{'a': 5, 'b': 'z'}, false, true],
    [{}, false, false],
    [{'a': 5, 'b': 'z'}, [], true],
    [{}, [], false],
    [{'a': 5, 'b': 'z'}, {}, true],
    [{}, {}, false],
  ],
  'logical_xor': [
    [7, 8, false],
    [7, 0, true],
    [7, 'xyz', false],
    [7, '', true],
    [7, true, false],
    [7, false, true],
    [7, [3, 5], false],
    [7, [], true],
    [7, {'a': 5, 'b': 'z'}, false],
    [7, {}, true],
    ['xyz', 8, false],
    ['xyz', 0, true],
    ['xyz', 'z', false],
    ['xyz', '', true],
    ['xyz', true, false],
    ['xyz', false, true],
    ['xyz', [3, 5], false],
    ['xyz', [], true],
    ['xyz', {'a': 5, 'b': 'z'}, false],
    ['xyz', {}, true],
    [true, 8, false],
    [true, 0, true],
    [true, 'z', false],
    [true, '', true],
    [true, true, false],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [3, 5], false],
    [true, [], true],
    [true, {'a': 5, 'b': 'z'}, false],
    [true, {}, true],
    [[3, 5], 8, false],
    [[3, 5], 0, true],
    [[3, 5], 'z', false],
    [[3, 5], '', true],
    [[3, 5], true, false],
    [[3, 5], false, true],
    [[3, 5], [3, 5], false],
    [[3, 5], [], true],
    [[3, 5], {'a': 5, 'b': 'z'}, false],
    [[3, 5], {}, true],
    [{'a': 5, 'b': 'z'}, 8, false],
    [{'a': 5, 'b': 'z'}, 0, true],
    [{'a': 5, 'b': 'z'}, 'z', false],
    [{'a': 5, 'b': 'z'}, '', true],
    [{'a': 5, 'b': 'z'}, true, false],
    [{'a': 5, 'b': 'z'}, false, true],
    [{'a': 5, 'b': 'z'}, [3, 5], false],
    [{'a': 5, 'b': 'z'}, [], true],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, {}, true],
  ],
  'equal': [
    [7, 7, true],
    [7, 0, false],
    [7, '7', true],
    [7, 'xyz', false],
    [7, true, true],
    [7, false, false],
    [0, false, true],
    [7, [3, 5], false],
    [7, {'a': 5, 'b': 'z'}, false],
    ['7', 7, true],
    ['xyz', 7, false],
    ['xyz', 'xyz', true],
    ['xyz', 'abc', false],
    ['xyz', true, true],
    ['xyz', false, false],
    ['', false, true],
    ['xyz', [3, 5], false],
    ['xyz', {'a': 5, 'b': 'z'}, false],
    [true, 7, true],
    [true, 0, false],
    [false, 0, true],
    [true, 'xyz', true],
    [true, '', false],
    [false, '', true],
    [true, true, true],
    [true, false, false],
    [false, true, false],
    [false, false, true],
    [true, [3, 5], false],
    [true, {'a': 5, 'b': 'z'}, false],
    [[3, 5], 7, false],
    [[3, 5], 'xyz', false],
    [[3, 5], true, false],
    [[3, 5], [3, 5], true],
    [[3, 5], [3, 'ab'], false],
    [[3, 5], {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, 7, false],
    [{'a': 5, 'b': 'z'}, 'xyz', false],
    [{'a': 5, 'b': 'z'}, true, false],
    [{'a': 5, 'b': 'z'}, [3, 5], false],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, true],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 8}, false],
  ],
  'notequal': [
    [7, 7, false],
    [7, 0, true],
    [7, '7', false],
    [7, 'xyz', true],
    [7, true, false],
    [7, false, true],
    [0, false, false],
    [7, [3, 5], true],
    [7, {'a': 5, 'b': 'z'}, true],
    ['7', 7, false],
    ['xyz', 7, true],
    ['xyz', 'xyz', false],
    ['xyz', 'abc', true],
    ['xyz', true, false],
    ['xyz', false, true],
    ['', false, false],
    ['xyz', [3, 5], true],
    ['xyz', {'a': 5, 'b': 'z'}, true],
    [true, 7, false],
    [true, 0, true],
    [false, 0, false],
    [true, 'xyz', false],
    [true, '', true],
    [false, '', false],
    [true, true, false],
    [true, false, true],
    [false, true, true],
    [false, false, false],
    [true, [3, 5], true],
    [true, {'a': 5, 'b': 'z'}, true],
    [[3, 5], 7, true],
    [[3, 5], 'xyz', true],
    [[3, 5], true, true],
    [[3, 5], [3, 5], false],
    [[3, 5], [3, 'ab'], true],
    [[3, 5], {'a': 5, 'b': 'z'}, true],
    [{'a': 5, 'b': 'z'}, 7, true],
    [{'a': 5, 'b': 'z'}, 'xyz', true],
    [{'a': 5, 'b': 'z'}, true, true],
    [{'a': 5, 'b': 'z'}, [3, 5], true],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 8}, true],
  ],
  'less': [
    [7, 8, true],
    [7, 7, false],
    [7, '8', true],
    [7, 'xyz', false],
    [0, true, true],
    [7, true, false],
    [7, [3, 5], false],
    [7, {'a': 5, 'b': 'z'}, false],
    ['5', 6, true],
    ['xyz', 6, false],
    ['xyz', 'xzz', true],
    ['xyz', 'xyy', false],
    ['', true, true],
    ['xyz', true, false],
    ['xyz', [3, 5], false],
    ['xyz', {'a': 5, 'b': 'z'}, false],
    [false, 7, true],
    [true, 7, false],
    [false, 'xyz', true],
    [true, 'xyz', false],
    [true, true, false],
    [true, false, false],
    [false, true, true],
    [false, false, false],
    [false, [3, 5], false],
    [false, {'a': 5, 'b': 'z'}, false],
    [[3, 5], 7, false],
    [[3, 5], 'xyz', false],
    [[3, 5], true, false],
    [[3, 5], [4, 6], true],
    [[3, 5], [3, 6], false],
    [[3, 5], {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, 7, false],
    [{'a': 5, 'b': 'z'}, 'xyz', false],
    [{'a': 5, 'b': 'z'}, true, false],
    [{'a': 5, 'b': 'z'}, [3, 5], false],
    [{'a': 5, 'b': 'y'}, {'a': 6, 'b': 'z'}, true],
    [{'a': 5, 'b': 'y'}, {'a': 5, 'b': 'z'}, false],
  ],
  'greater': [
    [7, 6, true],
    [7, 7, false],
    [7, '6', true],
    [7, 'xyz', false],
    [7, false, true],
    [7, true, false],
    [7, [3, 5], false],
    [7, {'a': 5, 'b': 'z'}, false],
    ['5', 4, true],
    ['3', 4, false],
    ['xyz', 'xyy', true],
    ['xyz', 'xzz', false],
    ['xyz', false, true],
    ['xyz', true, false],
    ['xyz', [3, 5], false],
    ['xyz', {'a': 5, 'b': 'z'}, false],
    [true, 0, true],
    [true, 1, false],
    [true, '', true],
    [true, 'xyz', false],
    [true, true, false],
    [true, false, true],
    [false, true, false],
    [false, false, false],
    [true, [3, 5], false],
    [true, {'a': 5, 'b': 'z'}, false],
    [[3, 5], 0, false],
    [[3, 5], '', false],
    [[3, 5], false, false],
    [[3, 5], [2, 4], true],
    [[3, 5], [2, 5], false],
    [[3, 5], {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, 0, false],
    [{'a': 5, 'b': 'z'}, '', false],
    [{'a': 5, 'b': 'z'}, false, false],
    [{'a': 5, 'b': 'z'}, [3, 5], false],
    [{'a': 5, 'b': 'z'}, {'a': 4, 'b': 'y'}, true],
    [{'a': 5, 'b': 'z'}, {'a': 4, 'b': 'z'}, false],
  ],
  'lessequal': [
    [7, 7, true],
    [7, 6, false],
    [7, '7', true],
    [7, 'xyz', false],
    [1, true, true],
    [1, false, false],
    [7, [3, 5], false],
    [7, {'a': 5, 'b': 'z'}, false],
    ['5', 5, true],
    ['5', 4, false],
    ['xyz', 'xyz', true],
    ['xyz', 'xyy', false],
    ['xyz', true, true],
    ['xyz', false, false],
    ['xyz', [3, 5], false],
    ['xyz', {'a': 5, 'b': 'z'}, false],
    [true, 1, true],
    [true, 0, false],
    [true, 'xyz', true],
    [true, '', false],
    [true, true, true],
    [true, false, false],
    [false, true, true],
    [false, false, true],
    [true, [3, 5], false],
    [true, {'a': 5, 'b': 'z'}, false],
    [[3, 5], 7, false],
    [[3, 5], 'xyz', false],
    [[3, 5], true, false],
    [[3, 5], [3, 5], true],
    [[3, 5], [2, 5], false],
    [[3, 5], {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, 7, false],
    [{'a': 5, 'b': 'z'}, 'xyz', false],
    [{'a': 5, 'b': 'z'}, true, false],
    [{'a': 5, 'b': 'z'}, [3,5], false],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, true],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'y'}, false],
  ],
  'greaterequal': [
    [7, 7, true],
    [7, 8, false],
    [7, '7', true],
    [7, 'xyz', false],
    [7, true, true],
    [0, true, false],
    [7, [], false],
    [7, {}, false],
    ['7', 7, true],
    ['7', 8, false],
    ['xyz', 'xyz', true],
    ['xyz', 'xzz', false],
    ['xyz', true, true],
    ['xyz', false, true],
    ['xyz', [], false],
    ['xyz', {}, false],
    [true, 1, true],
    [false, 2, false],
    [true, 'xyz', true],
    [false, 'xyz', false],
    [true, true, true],
    [true, false, true],
    [false, true, false],
    [false, false, true],
    [true, [3, 5], false],
    [true, {'a': 5, 'b': 'z'}, false],
    [[3, 5], 0, false],
    [[3, 5], '', false],
    [[3, 5], false, false],
    [[3, 5], [3, 5], true],
    [[3, 5], [3, 6], false],
    [[3, 5], {'a': 5, 'b': 'z'}, false],
    [{'a': 5, 'b': 'z'}, 0, false],
    [{'a': 5, 'b': 'z'}, '', false],
    [{'a': 5, 'b': 'z'}, false, false],
    [{'a': 5, 'b': 'z'}, [], false],
    [{'a': 5, 'b': 'z'}, {'a': 5, 'b': 'z'}, true],
    [{'a': 5, 'b': 'y'}, {'a': 5, 'b': 'z'}, false],
  ],
};

function _toString (value) {
  if (Array.isArray(value)) {
    return '[' + value.map(x => _toString(x)).join(', ') + ']';
  } else if (value instanceof Object) {
    return '{' + Object.keys(value).map(x => `'${x}': ${_toString(value[x])}`).join(', ') + '}';
  } else if (typeof value === 'string') {
    return `'${value}'`;
  } else if (typeof value === 'undefined') {
    return `undefined`;
  } else if (isNaN(value)) {
    return 'NaN';
  } else if (value === Infinity) {
    return 'Infinity';
  } else if (value === -Infinity) {
    return '-Infinity';
  } else {
    return `${value}`;
  }
}

function compare (val1, val2) {
  if (val1 instanceof Object && val2 instanceof Object) {
    const keys1 = Object.keys(val1);
    const keys2 = Object.keys(val2);
    if (keys1.length !== keys2.length) {
      return false;
    } else {
      return keys1.reduce((pv, cv) => pv && keys2.indexOf(cv) >= 0 && compare(val1[cv], val2[cv]), true);
    }
  } else if (val1 instanceof Object || val2 instanceof Object) {
    return false;
  } else if (typeof val1 === 'string' && typeof val2 === 'string') {
    return val1 === val2;
  } else if (isNaN(val1) && isNaN(val2)) {
    return true;
  } else {
    return val1 === val2;
  }
}

function makeCase (opname) {
  if (!caseMap[opname]) { return }
  const values = [[7, 0, -1], ['5', '', 'xy'], [true, false], [[3,5], [3, 'ab']], [{a: 5, b: 8}, {a: 5, b: 'z'}]];
  console.log(`'${opname}': [`);
  for (let i1 = 0; i1 < values.length; i1++) {
    for (let j1 = 0; j1 < values.length; j1++) {
      for (let i2 = 0; i2 < values[i1].length; i2++) {
        for (let j2 = 0; j2 < values[j1].length; j2++) {
          const result = _operator[opname](values[i1][i2], values[j1][j2]);
          console.log(`  [${_toString(values[i1][i2])}, ${_toString(values[j1][j2])}, ${_toString(result)}],`);
        }
      }
    }
  }
  console.log(`],`);
}

function testCase (opname) {
  if (!caseMap[opname]) { return }
  let allvalid = true;
  for (let ci = 0; ci < caseMap[opname].length; ci++) {
    const result = _operator[opname](caseMap[opname][ci][0], caseMap[opname][ci][1]);
    if (compare(result, caseMap[opname][ci][2])) {
      // result is valid
    } else {
      console.log(`#Invalid ${opname}(${_toString(caseMap[opname][ci][0])}, ${_toString(caseMap[opname][ci][1])}) => ${_toString(result)} excepts ${_toString(caseMap[opname][ci][2])}`);
      allvalid = false;
    }
  }
  if (allvalid) {
    console.log(`#Valid ${opname}`)
  }
}

function toMarkdown (opname) {
  if (!caseMap[opname]) { return }

  const opmap = {
    'add': '+',
    'subtract': '-',
    'multiply': '*',
    'divide': '/',
    'power': '^',
    'modulo': '%',
    'bit_and': '&',
    'bit_or': '\\|',
    'bit_xor': '~',
    'bit_shift': '<<',
    'bit_unshift': '>>',
    'not': '!',
    'logical_and': '&&',
    'logical_or': '\\|\\|',
    'logical_xor': '~~',
    'equal': '=',
    'notequal': '<>',
    'less': '<',
    'greater': '>',
    'lessequal': '<=',
    'greaterequal': '>=',
  };

  function typeIndex (val) {
    if (Array.isArray(val)) {
      return 3;
    } else if (val instanceof Object) {
      return 4;
    } else {
      const type = typeof val;
      if (type === 'number') {
        return 0;
      } else if (type === 'string') {
        return 1;
      } else if (type === 'boolean') {
        return 2;
      }
    }
  }
  function toStrong (value) {
    if (Array.isArray(value)) {
      return '[' + value.map(x => toStrong(x)).join(', ') + ']';
    } else if (value instanceof Object) {
      return '{' + Object.keys(value).map(x => `'${x}': ${toStrong(value[x])}`).join(', ') + '}';
    } else if (typeof value === 'string') {
      return `'${value}'`;
    } else if (typeof value === 'undefined') {
      return '`undefined`';
    } else if (value === null) {
      return '`null`';
    } else if (isNaN(value)) {
      return '`NaN`';
    } else if (value === Infinity) {
      return '`Infinity`';
    } else if (value === -Infinity) {
      return '`-Infinity`';
    } else {
      return `${value}`;
    }
  }
  const strs = [[[], [], [], [], []], [[], [], [], [], []], [[], [], [], [], []], [[], [], [], [], []], [[], [], [], [], []]];
  for (let ci = 0; ci < caseMap[opname].length; ci++) {
    const ii = typeIndex(caseMap[opname][ci][0]);
    const jj = typeIndex(caseMap[opname][ci][1]);
    const val1 = toStrong(caseMap[opname][ci][0]);
    const val2 = toStrong(caseMap[opname][ci][1]);
    const result = toStrong(caseMap[opname][ci][2]);
    if (caseMap[opname][ci][3] === 'anycase') {
      strs[ii][jj] = [`${result}`];
    } else if (Number.isInteger(ii) && Number.isInteger(jj)) {
      strs[ii][jj].push(`${val1}\`${opmap[opname]}\`${val2}=${result}`);
    } else if (Number.isInteger(ii) && !Number.isInteger(jj)) {
      strs[0][ii].push(`\`${opmap[opname]}\`${val1}=${result}`);
    }
  }
  const lines = [];
  lines.push(`|Left\Right|Number|String|Boolean|Array|Object|`);
  lines.push(`|---|---|---|---|---|---|`);
  lines.push('|Number|' + strs[0].map(x => x.join('<br>')).join('|') + '|');
  lines.push('|String|' + strs[1].map(x => x.join('<br>')).join('|') + '|');
  lines.push('|Boolean|' + strs[2].map(x => x.join('<br>')).join('|') + '|');
  lines.push('|Array|' + strs[3].map(x => x.join('<br>')).join('|') + '|');
  lines.push('|Object|' + strs[4].map(x => x.join('<br>')).join('|') + '|');
  lines.forEach(x => console.log(x));
}

let level = 'info';
let cmd = '';
let opnames = [];
for (let ai = 2; ai < process.argv.length; ai++) {
  if (process.argv[ai] === '-v') {
    level = process.argv[++ai];
  } else if (!process.argv[ai].startsWith('-')) {
    if (!cmd) {
      cmd = process.argv[ai];
    } else {
      opnames.push(process.argv[ai]);
    }
  }
}
if (level === 'info') {
  console.debug = () => undefined;
}
if (!cmd) {
  cmd = 'test';
}
if (opnames.length === 0) {
  opnames = Object.keys(caseMap);
}
setTimeout(() => {
  if (cmd === 'test') {
    opnames.forEach(x => testCase(x));
  } else if (cmd === 'make') {
    opnames.forEach(x => makeCase(x));
  } else if (cmd === 'markdown') {
    opnames.forEach(x => toMarkdown(x));
  }
}, 0);
